posts:
  - title: "the second blog post"
    href: "/blog/posts/2"
    teaser: "This is the second example post"
    color_theme: "hsl(260, 58%, 64%)"
    date: "NONE"
  - title: "A new start!"
    href: "/blog/posts/a_new_start!.html"
    teaser: "My first post, explaining how this site is a fresh start for me in terms of internet presence and what inspired me to start this website."
    color_theme: "hsl(120, 58%, 64%)"
    date: "5/28/25"
