images:
  - path: _7171912.jpg
    alt: An image with multiple semi-transparent figures with only an upper body and head
    subtext: (uneditted) handheld flash self-portrait
    category: people
  - path: _7171899.jpg
    alt: An image with a semi-transparent figures with only an upper body and head
    subtext: (uneditted) handheld flash self-portrait
    category: people
  - path: _7171924.jpg
    alt: an image with multiple semi-transparent figures running in a single exposure
    subtext: (uneditted) multiflash me and partner
    category: people
  - path: _7171922.jpg
    alt: an image with multiple semi-transparent figures walking in a single exposure
    subtext: (uneditted) multiflash self-portrait
    category: people
  - path: _7051685.jpg
    alt: Me infront of flowers
    subtext: (picture of me taken by partner)
    category: people
  - path: _7051686.jpg
    alt: Me infront of flowers
    subtext: (picture of me taken by partner)
    category: people
  - path: _7051687.jpg
    alt: Me infront of flowers
    subtext: (picture of me taken by partner)
    category: people
  - path: _7051742.jpg
    alt: Me curled up on bench
    subtext: (picture of me taken by partner)
    category: people
  - path: _7051749.jpg
    alt: Me sitting on truck receiving dock
    subtext: (picture of me taken by partner)
    category: people
  - path: _7051753.jpg
    alt: Me sitting on truck receiving dock
    subtext: (picture of me taken by partner)
    category: people
  - path: _3110567.jpg
    alt: Subway connecting to skyscraper, another skyscraper reflecting off the glass.
    subtext: Downtown skyscrapers
    category: street
  - path: _3110555.jpg
    alt: Light rail arriving with motion blur
    subtext: Light rail arriving
    category: street
    info_page: light_rail_arriving.html
  - path: _3110547.jpg
    alt: Kid biking in downtown area with motion blur
    subtext: Downtown biker kid
    category: street
  - path: _3110539_01.jpg
    alt: 2 skyscrapers filling the frame, one reflecting off the other's windows
    subtext: Downtown skyscrapers
    category: street
  - path: _3260480.jpg
    alt: Orange cat laying down
    subtext: Midnight cat (zzzmeowzzz)
    category: cats
  - path: _1099339.jpg
    alt: Orange cat laying down
    subtext: Mebow
    category: cats
  - path: _9262554.jpg
    alt: Orange cat sitting down
    subtext: Mewow
    category: cats
  - path: _3170093.jpg
    alt: My partner who is a very cool looking person sitting on stairs
    subtext: Partner looking cool on stairs
    category: people
  - path: 3170047_03.jpg
    alt: My partner who is a very cool looking person smiling with a natural green background
    subtext: Partner headshot (meow)
    category: people
    info_page: partner_headshot.html
  - path: _A013142_01.jpg
    alt: Turkey walking in an urban area
    subtext: City turkey
    category: birds
  - path: _4070707.jpg
    alt: Goose taking a stroll
    subtext: Goose taking a stroll (cutely)
    category: birds
  - path: _4070807.jpg
    alt: Pair of geese sitting at the side of a river
    subtext: Pair of geese hanging out (cutely)
    category: birds
  - path: _4070717.jpg
    alt: Two geese standing in front of one another, giving the appearance of a single goose with two heads.
    subtext: The fabled two headed goose
    category: birds
  - path: _4070870.jpg
    alt: Turkey showing
    subtext: Turkey breeding season
    category: birds
  - path: _B018231.jpg
    alt: a policeman standing a crime scene behind yellow caution tape
    subtext: November 2024 Dinkytown shooting
    category: street
    info_page: nov_2024_dinkytown_shooting.html
  - path: _A153796_01.jpg
    alt: Turkey taking a walk
    subtext: Turkey taking a walk
    category: birds
  - path: _A156858_01.jpg
    alt: Turkey taking a walk with fluffed back feathers
    subtext: Turkey with fluffy tail feathers
    category: birds
  - path: _A156841_01.jpg
    alt: Yet another turkey taking a walk
    subtext: Turkey taking a walk
    category: birds
  - path: _A156091.jpg
    alt: A turkey eating a berry off a vine wall
    subtext: Turkey eating a berry
    category: birds
  - path: _A155961.jpg
    alt: A closeup shot of a turkey, with a vine wall background
    subtext: Curious turkey
    category: birds
  - path: _A155670.jpg
    alt: A turkey flapping it's wings
    subtext: Turkey exercising it's wings
    category: birds
  - path: _A154068_03.jpg
    alt: A picture of a turkey peaking around a brick wall outside
    subtext: Wild city turkey
    category: birds
  - path: _A156233_01.jpg
    alt: A closeup shot of a turkey sitting down with a brick wall in the background
    subtext: Wild city turkey relaxing
    category: birds
  - path: _A156226_02.jpg
    alt: A closeup shot of a turkey, with a blurred natural background
    subtext: A turkey's Linkedin photo
    category: birds
    info_page: turkey_linkedin.html
  - path: _A053524.jpg
    alt: My partner who is a very cool looking person in a night time scene
    subtext: Partner at night (meow)
    category: people
  - path: _9170876.jpg
    alt: Ostrich
    subtext: Ostrich
    category: birds
    info_page: ostrich.html
  - path: _9170911.jpg
    alt: Ostrich
    subtext: Ostrich with impressive neck
    category: birds
    info_page: ostrich.html
  - path: _9170956.jpg
    alt: Ostrich
    subtext: Ostrich taking dust bath
    category: birds
    info_page: ostrich.html
  - path: _9170995.jpg
    alt: Ostrich
    subtext: Ostrich
    category: birds
    info_page: ostrich.html
