birds:
  - path: _9170876.jpg
    alt: rascal
    subtext: Rascal
  - path: _9170911.jpg
    alt: rascal
    subtext: Rascal
  - path: _9170956.jpg
    alt: rascal
    subtext: Rascal
  - path: _9170995.jpg
    alt: rascal
    subtext: Rascal