birds:
  - path: _9170876.jpg
    alt: rascal
    subtext: Rascal
  - path: _9170911.jpg
    alt: rascal
    subtext: Rascal
  - path: _9170956.jpg
    alt: rascal
    subtext: Rascal
  - path: _9170995.jpg
    alt: rascal
    subtext: Rascal

people:
  - path: _A053524.jpg
    alt: Jo
    subtext: Jo at night (meow)
