name: publish action

on:
  push:
    branches:
      - "master"

jobs:
  publish:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip' # caching pip dependencies

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate your content
        run: "cd generator && python main.py"

      - name: Remove gitignore
        run: "rm .gitignore"

      - name: Publish current workdir
        uses: rayluo/github-pages-overwriter@v1.3
        with:
          source-directory: out
          target-branch: gh-pages
